{{- if .Values.ingress.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: code-server
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`code.daystram.com`)
      middlewares:
        - name: vpn-whitelist
          namespace: ingress-traefik
      services:
        - name: code-server
          passHostHeader: true
          port: 8080
  tls:
    secretName: cert-code-server

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: code-server
spec:
  dnsNames:
    - code.daystram.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: cert-code-server
{{- end }}
