apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: factorio
spec:
  entryPoints:
    - factorio
  routes:
    - match: HostSNI(`*`)
      services:
        - name: factorio
          port: 34197

---
apiVersion: v1
kind: Service
metadata:
  name: factorio
spec:
  ports:
    - protocol: UDP
      port: 34197
      targetPort: 34197

---
apiVersion: v1
kind: Endpoints
metadata:
  name: factorio
subsets:
  - addresses:
      - ip: 10.7.7.2
    ports:
      - port: 34197
